feat: add createVillus
logaretm/villus pull request #83
Opened 2020-11-24 11:13 UTC by sibbng

2020-11-25 11:51 UTC, logaretm requested changes
Thank you for the PR, I don't mind merging it but I want to explore other API options. as `createVillus` would be yet another way to create a villus client which seems redundant.

Adding an `install` method on the `Client` class seems to be reasonable as then we can reuse the `createClient` function as a Vue plugin.

for example:

```js
Vue.use(createClient({ url: ... }));
```

2020-11-25 12:46 UTC, sibbng commented
Can you take it? I didn't get success. Classes 😓

2020-11-26 23:39 UTC, logaretm approved these changes

2020-11-26 23:40 UTC, merged

2020-11-26 23:40 UTC, logaretm commented
Thank you, I will document this and release it.